apiVersion: v2
appVersion: stable-latest
description: Meshery Adapter for NGINX Service Mesh.
icon: https://meshery.io/images/logos/meshery-logo.png
maintainers:
- email: community@layer5.io
  name: Layer5 Authors
- email: panyuenlau@gmail.com
  name: darrenlau
- email: lee.calcote@layer5.io
  name: leecalcote
name: meshery-nginx-sm
type: application
version: 0.5.0
